models/Order.php
<?php

namespace app\models;

use yii\helpers\ArrayHelper;
use Yii;

/**
 * This is the model class for table "order".
 *
 * @property integer $id
 * @property integer $userId
 * @property integer $mealId
 * @property string $orderDate
 * @property string $lastUpdate
 * @property integer $shift
 * @property integer $categoryTypeId
 * @property integer $categoryId
 * @property integer $status
 * @property string $comment
 *
 * @property User $user
 * @property Categorytype $categoryType
 * @property Category $category
 */
class Order extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'order';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['userId', 'mealId', 'shift', 'categoryTypeId', 'categoryId'], 'required'],
            [['userId', 'mealId', 'shift', 'categoryTypeId', 'categoryId', 'status'], 'integer'],
//            [['orderDate', 'lastUpdate'], 'safe'],
            [['userId', 'mealId', 'orderDate', 'lastUpdate', 'shift', 'categoryTypeId', 'categoryId', 'status', 'comment', 'extras'], 'safe'],
            [['userId', 'mealId', 'shift', 'categoryTypeId', 'categoryId', 'status'], 'integer'],
            [['comment'], 'string', 'max' => 255],
            [['userId'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['userId' => 'Id']],
            [['categoryTypeId'], 'exist', 'skipOnError' => true, 'targetClass' => Categorytype::className(), 'targetAttribute' => ['categoryTypeId' => 'id']],
            [['categoryId'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['categoryId' => 'id']],
            [['orderExtras'], 'string', 'max' => 777]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'Id' => 'ID',
            'userId' => 'User ID',
            'mealId' => 'Meal ID',
            'orderDate' => 'Order Date',
            'lastUpdate' => 'Last Update',
            'shift' => 'Shift',
            'categoryTypeId' => 'Category Type ID',
            'categoryId' => 'Category ID',
            'status' => 'Status',
            'comment' => 'Comment',
            'orderExtras' => 'Extras',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    
    public function getVendor() {
        return $this->hasMany(Vendor::className(), ['id' => 'vendorId'])->viaTable('meal', ['id' => 'mealId']);
    }
    
    public function getUser() {
        return $this->hasOne(User::className(), ['Id' => 'userId']);
    }
    
    public function getMeal() {
        return $this->hasOne(Meal::className(), ['id' => 'mealId']);
    }
       

    public function getUserItem() {
        return $this->hasOne(User::className(), ['Id' => 'userId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryType() {
        return $this->hasOne(Categorytype::className(), ['id' => 'categoryTypeId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory() {
        return $this->hasOne(Category::className(), ['id' => 'categoryId']);
    }
    
    public function getShift() {
        return $this->hasMany(Shift::className(), ['shiftId' => 'shift']);
    }    
/*
    public function getShiftsItem() {
        return $this->hasOne(Shift::className(), ['shiftId' => 'shift']);
    }
*/
    public function getMealItem() {
        return $this->hasOne(Meal::className(), ['id' => 'mealId']);
    }

    public function getStatusItem() {
        return $this->hasOne(Status::className(), ['id' => 'status']);
    }

    //count Order function
    public static function countOrders() {
        return self::find()->count();
    }

    ////////////////////////////

    public function getUserOrders($userID) {
        $orders = array();

        $allOrders = Order::find()
            ->where(['userId' => $userID])
            ->all();

        foreach ($allOrders as $key => $value) {
            switch ($value['shift']) {
                case 1:
                    $value['orderDate'] = date('Y-m-d\TH:i:s\Z', strtotime(substr($value['orderDate'], 0, 10) . ' 08:00:00'));
                    break;
                case 2:
                    $value['orderDate'] = date('Y-m-d\TH:i:s\Z', strtotime(substr($value['orderDate'], 0, 10) . ' 12:00:00'));
                    break;
                case 3:
                    $value['orderDate'] = date('Y-m-d\TH:i:s\Z', strtotime(substr($value['orderDate'], 0, 10) . ' 18:00:00'));
                    break;
                case 4:
                    $value['orderDate'] = date('Y-m-d\TH:i:s\Z', strtotime(substr($value['orderDate'], 0, 10) . ' 23:00:00'));
                    break;
            }

            $mealName = Meal::find()
                ->where(['Id' => $value['mealId']])
                ->one();
            // file_put_contents("/var/www/html/testYair.log", 'key' . $value['id'] . 'title' . $mealName['name'] . 'start' . $value['orderDate'] ."\n" , FILE_APPEND);
            $orders[] = ['key' => $value['id'], 'title' => $mealName['name'], 'start' => $value['orderDate']];
        }

        return $orders;
    }
}

controllers/OrderController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Order;
use app\models\OrderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Query;
use yii\helpers\Json;
use yii\data\SqlDataProvider;
//use yii\base\Event;
//use yii\web\Response;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller {

    public function beforeAction($action) {
        if (Yii::$app->language == "he") 
        {
        ?>
            <link href="/rafafoodproject/web/assets/8b0376e8/css/bootstrap.css" rel="stylesheet">
            <link href="/rafafoodproject/web/assets/8b0376e8/css/bootstrap-rtl.css" rel="stylesheet">
        <?php
        } 
        else 
        {
        ?>
            <link href="/rafafoodproject/web/assets/8b0376e8/css/bootstrap.css" rel="stylesheet">
        <?php
        }

        return parent::beforeAction($action);
    }

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
               
        return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Order();
        
        if (Yii::$app->request->post()) 
        {
            $datesArray = explode(",", $_POST['dates']);

            for ($x = 0; $x < count($datesArray); $x++) {
                $model = new Order();
                //$model->attributes = Yii::$app->request->post('Order');

                if (!empty($_POST['mealExtras']))
                    $model->orderExtras = implode(",", $_POST['mealExtras']);
                
                if ($_POST['employeeID'] == "")
                    $model->userId = Yii::$app->user->getId();
                else
                    $model->userId = $_POST['employeeID']; 
                
                $model->mealId = $_POST['mealID'];
                $model->orderDate = $datesArray[$x];
                $model->lastUpdate = date('Y-m-d H:i:s');
                $model->shift = $_POST['shift'];
                $model->categoryTypeId = $_POST['categoryTypeId'];
                $model->categoryId = $_POST['orderCategoryID'];

                //$model->status = $_POST['Order']['status'];
                if ($_POST['comment'])
                    $model->comment = $_POST['comment'];
                try 
                {
                    if ($model->save(false))
                    {
                     //  file_put_contents("/var/www/html/testYair.log", "aa" . "\n" , FILE_APPEND); 
                        echo "SUCCESS ";
                        $this->render('display_orders', [
                            'model' => $model,
                        ]);
                    }
                    else
                    {
                        echo "FAILURE: ";
                    }
                } 
                catch (\Exception $e) 
                {
                    // throw new \yii\web\HttpException(405, 'שימוש ב ctrl + R אסור בנקודה זו');
                    Yii::$app->session->setFlash('success', 'שימוש ב ctrl + R אסור בנקודה זו');
                    echo "FAILURE: " . $e->getMessage() . "\n";
                   //file_put_contents("/var/www/html/testYair.log", "error: " . print_r($e->getMessage(), true) . "\n" , FILE_APPEND);
                    return $this->render('display_orders', [
                       'model' => $model,
                    ]);
                }
            }
            return $this->render('display_orders', [
                'model' => $model,
            ]);                
        }
        else 
        {
            echo "failure";
            return $this->render('create', [
                    'model' => $model,
            ]);
        }

        /*
          if ($model->load(Yii::$app->request->post()) && $model->save()) {
          return $this->redirect(['view', 'id' => $model->id]);
          } else {
          return $this->render('create', [
          'model' => $model,
          ]);
          }
         */
        return $this->render('display_orders', [
           'model' => $model,
        ]);
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    
    public function actionUpdate($id) {
    //public function actionUpdate() {    
        $model = $this->findModel($id);

        if (Yii::$app->request->isAjax) 
        { 
            
            if (!empty($_GET['mealExtras']))
                    $model->orderExtras = implode(",", $_GET['mealExtras']);
            
            if ($_GET['employeeID'] == "null" || $_GET['employeeID'] == "undefined")
                $model->userId = Yii::$app->user->getId();
            else
                $model->userId = $_GET['employeeID'];
            $model->mealId = $_GET['mealID'];
            //$model->orderDate = $_GET['orderDate'];
            $model->lastUpdate = date('Y-m-d H:i:s');
            $model->shift = $_GET['shift'];

            $model->categoryTypeId = $_GET['categoryTypeId'];
            $model->categoryId = $_GET['orderCategoryID'];
            //$model->status = $_POST['Order']['status'];
            if ($_GET['comment'])
                $model->comment = $_GET['comment'];
            try 
            {
                if ($model->save(false))
                {
                    //file_put_contents("/var/www/html/testYair.log", "aa" . "\n" , FILE_APPEND); 
                    echo "SUCCESS ";
                    $this->render('display_orders', [
                        'model' => $model,
                    ]);
                }
                else
                {
                    echo "FAILURE: ";
                }
            } 
            catch (\Exception $e) 
            {
                // throw new \yii\web\HxttpException(405, 'שימוש ב ctrl + R אסור בנקודה זו');
                Yii::$app->session->setFlash('success', 'שימוש ב ctrl + R אסור בנקודה זו');
                echo "FAILURE: " . $e->getMessage() . "\n";
                //file_put_contents("/var/www/html/testYair.log", "error: " . print_r($e->getMessage(), true) . "\n" , FILE_APPEND);
                return $this->render('display_orders', [
                   'model' => $model,
                ]);
            }

            return $this->render('display_orders', [
                'model' => $model,
            ]);                
        }
        else 
        {
            echo "failure";
            return $this->render('update', [
                'model' => $model,
            ]);
        }

        return $this->render('display_orders', [
            'model' => $model,
            'employee' => $model->userId,
        ]);

/* 
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            file_put_contents("/var/www/html/testYair.log", "in save: " . "\n" , FILE_APPEND); 
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                    'model' => $model,
            ]);
        }
*/
    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();
        $model = new Order();

        return $this->render('display_orders', [
            'model' => $model,
        ]);              
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionDisplay_orders() {
        $model = new Order();
        return $this->render('display_orders', [
            'model' => $model,
        ]);
    }

    public function actionGet_order() {    
        if (Yii::$app->request->isAjax) {
            $data = Yii::$app->request->post();
            $orderDate = $data['date'];
            $userID = $data['userID'];
            
            $sql = 'SELECT * FROM `order` WHERE userId = ' . $userID . ' AND orderDate = "' . $orderDate . '"';

            try
            {
                $connection = Yii::$app->db;
                $model = $connection->createCommand($sql);
                $rows = $model->queryOne();    
                
                if (empty($rows))
                   return "!@#" . 0 . "!@#";
                else
                    return "!@#" . 1 . "!@#";
            } 
            catch (\Exception $e) 
            {

views/order/_displayOrders.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = 'Display Order';
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-display">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('displayOrders', [	
        'model' => $model,
    ]) ?>

</div>

views/order/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\models\Shift;
use app\models\Categorytype;
use app\models\Category;
use kartik\depdrop\DepDrop;
use yii\bootstrap\ButtonGroup

/* @var $this yii\web\View */
/* @var $model app\models\Order */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-form">

    <?php
    $form = ActiveForm::begin([
            'id' => 'getOrder-form',
        ])
    ?>    
    
    <div class="form-group field-order-shift required">
        <label class="control-label">בחר משמרת</label>
        <input type="hidden" name="Order[shift]" id="orderShiftID" value="">
        <div id="order-shift" aria-required="true"></div> 
    </div>

    <div class="form-group required" id="categoryTypeID">
        <label class="control-label">בחר סוג</label>
        <input type="hidden" name="Order[categoryTypeId]" id="orderCategoryTypeID" value="">
        <div id="order-categorytypeid" aria-required="true"></div>
    </div>
    
    <div class="clearfix" id='mealTypeID'>
        <label class="control-label">Category ID</label>
        <div class="form-group field-order-categoryid required">
            <input type="hidden" name="Order[categoryId]" id="orderCategoryID" value="">
            <div id="order-categoryid" aria-required="true">
                <div class="help-block"></div>
            </div>	
        </div>
    </div>

    <div id='mealID'>
        <div class="form-group field-order-mealId required">
            <label class="control-label">meals</label>
            <input type="hidden" name="Order[mealId]" id="orderMealID" value="">
            <div id="order-meal" aria-required="true">
                <table id="mealTable" class="table table-striped table-bordered table-sm table-responsive">
                    <thead class="thead-dark">
                        <tr>
                            <th id="ID">ID</th>
                            <th>name</th>
                            <th>תוספות</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <div class="help-block"></div>
            </div>	
        </div>
    </div>

    <?= $form->field($model, 'comment')->textarea (array('id' => 'orderComment', 'maxlength' => true, 'rows' => 6, 'cols' => 50)) ?>

    <div class="form-group">
        <?= Html::submitButton('Create', ['id' => 'submitCreate', 'class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script>
    $(document).ready(function () {
        var shift = "";
        var categoryTypeID = "";
        var orderCategoryID = "";
        var mealType = "";
        var mealID = "";
        
        $(document).on("beforeSubmit", "#getOrder-form", function () {
            // send data to actionSave by ajax request.
            return false; // Cancel form submitting.
        });

        $('#categoryTypeID').hide();
        $('#mealTypeID').hide();
        $('#mealID').hide();  
        $('#submitCreate').attr('disabled','disabled');
        
        var url = window.location.href;
        var res = url.split("/");  //split by space
        var targetDates = getParameterByName('dates');
        var employeeID = getParameterByName('employeeID');
        if (employeeID == "undefined")
            employeeID = ""        
        
        res.pop();  //remove last element
        res.pop();
        url = res.join("/") + "/shift/get_relevant_shifts";
        
        jQuery.ajax({
            type: 'get',
            data: {targetDates: targetDates, employeeID: employeeID},
            url: url,
            success: function (response) {
                response = removeHeader(response);
                $('#order-shift').html(response); 
                
                $('button[id^="shiftID"]').on('click', function() {  
                    shift = $(this).attr('value'); // Get the value attribute
                    $('#orderShiftID').val(shift);
                });
            },
            error: function () {
                console.log('failure');
            }
        });   

        $('#order-shift').click(function () {
           //alert(shift);
            $('#categoryTypeID').hide();
            $('#mealTypeID').hide();
            $('#mealID').hide(); 
            var url = window.location.href;
            var res = url.split("/");  //split by space
            res.pop();  //remove last element
            res.pop();
            url = res.join("/") + "/categorytype/get_category";
            jQuery.ajax({
                type: 'get',
                url: url,
                data: {shift: shift},
                success: function (response) {
                    response = removeHeader(response);
                    //console.log(response);
                    $('#order-categorytypeid').html(response);
                    $('#categoryTypeID').show();
                
                    $('button[id^="categoryTypeID"]').on('click', function() {  
                        categoryTypeID = $(this).attr('value'); // Get the value attribute
                        $('#orderCategoryTypeID').val(categoryTypeID);
                    });
                    //$('#categoryTypeID').show();
                    //$('#mealTypeID').show();
                    //return false;
                },
                error: function () {
                    console.log('failure');
                }
            });
        });  

        $('#order-categorytypeid').click(function () {
            //alert("categoryTypeID: " +categoryTypeID);
            $('#mealTypeID').hide();
            $('#mealID').hide();    
            var url = window.location.href;
            var res = url.split("/");  //split by space
            res.pop();  //remove last element
            res.pop();
            url = res.join("/") + "/category/get_meals_by_parameters";

            jQuery.ajax({
                type: 'post',
                data: {shift: shift, categoryType: categoryTypeID},
                url: url,
                success: function (response) {
                    response = removeHeader(response);
                    $('#order-categoryid').html(response);
                    $('#mealTypeID').show();
                    
					//need to display all of the options - כריכים, סלטים, טוסטים ושונות
                    $('button[id^="orderCategoryID"]').on('click', function() {  
						orderCategoryID = $(this).attr('value');// Get the value attribute
                        $('#orderCategoryID').val(orderCategoryID);
                    });                    
                },
                error: function () {
                    console.log('failure');
                }
            });            

        });

        $(document).on("click",".mealCategoryID",function(){    
            if (document.getElementById("mealTable").rows.length > 1)
            {
                for (var i = document.getElementById("mealTable").rows.length; i > 1;i--)
                {
                    //console.log("i" + i);
                    document.getElementById("mealTable").deleteRow(i - 1);
                }
            }
        
            mealType = orderCategoryID;
           // $('#orderCategoryID').val(mealType);
            //alert("mealType: " + mealType);
            var url = window.location.href;
            var res = url.split("/");  //split by space
            res.pop();  //remove last element
            res.pop();
            url = res.join("/") + "/meal/get_meals_by_parameters";
            
            jQuery.ajax({
                type: 'post',
                cache: false,
                data: {shift: shift, categoryType: categoryTypeID, mealType: orderCategoryID},
                url: url,
                success: function (response) {
                    response = removeHeader(response);
                    $('#mealTable').append(response);
                    //$('#order-meal').html(response);
                    $('#mealID').show();
                    /*
                    $('button[id^="mealsID"]').on('click', function() {  
                        mealID = $(this).attr('value'); // Get the value attribute
                        $('#orderMealID').val(mealID);
                    });                     
                    */
                },
                error: function () {
                    console.log('failure');
                }
            });            
        });
        
        $("#mealTable").on('click','td',function(){
             $("#mealTable tr").css('background', '');
             // get the current row
             var currentRow=$(this).closest("tr"); 

             var col1=currentRow.find("td:eq(0)").text(); // get current row 1st TD value
             //var col2=currentRow.find("td:eq(1)").text(); // get current row 2nd TD
            // var col3=currentRow.find("td:eq(2)").text(); // get current row 3rd TD
             //var data=col1+"\n"+col2+"\n";//+col3;

             //alert(data);
             currentRow.css('background', 'red');
             mealID = col1;
             
             if (mealID != "" && orderCategoryID != "" && shift != "" && categoryTypeID != "")
                 $('#submitCreate').removeAttr('disabled');
        });       
        
        $('#submitCreate').click(function () {
            var url = window.location.href;            
            var dates = getParameterByName('dates');

            var employeeID = getParameterByName('employeeID');
            if (employeeID == "undefined")
                employeeID = ""
            var mealExtras = $('#mealExtras').val();
            
            /*
            console.log("mealExtras: " + mealExtras);
            alert("mealExtras: " + mealExtras);
            
            throw new Error("Sorry, but you are too young for this movie");
            */
            var res = url.split("/");  //split by space
            res.pop();  //remove last element
            res.pop();
            url = res.join("/") + "/order/create";

            jQuery.ajax({
                type: 'post',
                //cache: false,
                data: {mealID: mealID, orderCategoryID: orderCategoryID, shift: shift, categoryTypeId: categoryTypeID, dates: dates, comment: $('#orderComment').val(), 
                    employeeID: employeeID, mealExtras: mealExtras},
                url: url,
                success: function (response) {
                    console.log('success');
                    var url = window.location.href;            
                    var res = url.split("/");  //split by space
                    res.pop();  //remove last element
                    res.pop();
                    url = res.join("/") + "/order/display_orders";                    
                    window.open(url + '?employeeID=' + employeeID, "_self");
                },
                error: function () {
                    console.log('failure');
                }
            }); 
        });
    });

    function removeHeader(response) {
        var n = response.indexOf("!@#");
        var response = response.substr(n + 3);
        //console.log('response: ' + response);

        var n = response.indexOf("!@#");
        var response = response.substr(0, n);

        return response;
    }

function getParameterByName(name, url) {
    if (!url) url = window.location.href;
    name = name.replace(/[\[\]]/g, "\\$&");
    var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
        results = regex.exec(url);
    if (!results) return null;
    if (!results[2]) return '';
    return decodeURIComponent(results[2].replace(/\+/g, " "));
}
</script>

views/order/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\grid\GridView;
use kartik\daterange\DateRangePicker;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model app\models\OrderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    
<?=  $form->field($model, 'orderDate', [
        //'addon'=>['prepend'=>['content'=>'<i class="glyphicon glyphicon-calendar"></i>']],
        'options'=>['class'=>'drp-container form-group']
    ])->widget(DateRangePicker::classname(), [
        'useWithAddon'=>false
    ]);   
?>    
    
    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'userId') ?>

    <?= $form->field($model, 'mealId') ?>

    <?php //echo $form->field($model, 'orderDate') ?>

    <?= $form->field($model, 'lastUpdate') ?>

    <?php // echo $form->field($model, 'shift') ?>

    <?php // echo $form->field($model, 'categoryTypeId') ?>

    <?php // echo $form->field($model, 'categoryId') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'comment') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/order/create.php
<?php

use yii\helpers\Html;
use yii\web\View;


/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = 'Create Order';
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

//$this->registerCssFile("https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css", ['position' => \yii\web\View::POS_HEAD]);
//$this->registerJsFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js', ['position' => \yii\web\View::POS_HEAD]);
    
?>
<div class="order-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/order/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = 'Update Order: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="order-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_update', [
        'model' => $model,
    ]) ?>

</div>